// Deterministic btop-shaped workload generation and duration-stable offscreen draw measurement.
import CoreGraphics
import Dispatch
import Foundation
import TerminalCore
import TerminalRenderExecution
import TerminalRenderPlanning

/// Names a fixed terminal geometry so benchmark results remain comparable between runs.
public struct DrawBenchmarkGrid: Codable, Equatable, Sendable {
    /// Number of cells in each generated row.
    public let columns: Int
    /// Number of rows in the generated viewport.
    public let rows: Int

    /// Allows tests and future benchmark grids to use the same workload contract.
    public init(columns: Int, rows: Int) {
        self.columns = columns
        self.rows = rows
    }

    /// Corpus-parity and realistic full-screen geometries measured by every run.
    public static let standard = [
        DrawBenchmarkGrid(columns: 80, rows: 24),
        DrawBenchmarkGrid(columns: 160, rows: 50),
    ]
}

/// Separates today's full draw cost from the intended few-row hot path.
public enum DrawBenchmarkScenario: String, Codable, CaseIterable, Sendable {
    case fullFrame = "full-frame"
    case damageClipped = "damage-clipped"
}

/// Retains raw batch totals alongside normalized draw durations to prove the timing floor.
public struct DrawBenchmarkMeasurements: Codable, Equatable, Sendable {
    /// Geometry used to construct the terminal and surface.
    public let grid: DrawBenchmarkGrid
    /// Drawing path measured by these samples.
    public let scenario: DrawBenchmarkScenario
    /// Fixed number of draws included in every raw sample.
    public let batchCount: Int
    /// Per-draw durations normalized from each fixed-batch total.
    public let drawDurationNanoseconds: [UInt64]
    /// Raw fixed-batch totals retained to prove the duration floor.
    public let sampleDurationNanoseconds: [UInt64]
}

/// Provides one stable JSON envelope for every grid and scenario in a benchmark run.
public struct DrawBenchmarkReport: Codable, Equatable, Sendable {
    /// Results in stable grid-major, scenario-minor order.
    public let measurements: [DrawBenchmarkMeasurements]

    /// Keeps all scenario results in one executable-boundary value.
    public init(measurements: [DrawBenchmarkMeasurements]) {
        self.measurements = measurements
    }
}

/// Reports an offscreen allocation failure instead of silently omitting a scenario.
public enum DrawBenchmarkError: Error {
    case invalidMetrics
    case invalidTerminal
    case invalidFrame
    case allocationFailed
}

/// Generates repeatable dense ANSI whose changing color and emphasis prevent adjacent text-run folding.
public func btopShapedANSI(for grid: DrawBenchmarkGrid) -> [UInt8] {
    let glyphs = ["┌", "─", "┐", "│", "⣿", "⣷", "⣯", "█", "▆", "▃", "└", "┘"]
    var output = "\u{1b}[?25l\u{1b}[H"
    for row in 0..<grid.rows {
        for column in 0..<grid.columns {
            let color = 16 + ((row * grid.columns + column) * 37) % 216
            let bold = (row + column).isMultiple(of: 2) ? "1" : "22"
            output += "\u{1b}[\(bold);38;5;\(color)m"
            output += glyphs[(row * 5 + column * 7) % glyphs.count]
        }
        if row + 1 < grid.rows {
            output += "\r\n"
        }
    }
    output += "\u{1b}[0m"
    return Array(output.utf8)
}

/// Feeds the generated bytes through the production terminal and planner used by the app.
public func makeBtopShapedPlan(for grid: DrawBenchmarkGrid) -> RenderFramePlan? {
    guard var terminal = Terminal(columns: grid.columns, rows: grid.rows) else { return nil }
    terminal.feed(btopShapedANSI(for: grid))
    return planFrame(
        for: terminal,
        presentation: RenderPresentation(
            theme: .dark,
            isCursorVisible: false,
            cursorShape: .block
        )
    )
}

/// Executes one scenario against an allocated sRGB bitmap and returns its byte count.
public func executeDrawScenario(
    _ scenario: DrawBenchmarkScenario,
    plan: RenderFramePlan,
    displayScale: CGFloat = 2
) throws -> Int {
    let prepared = try PreparedDraw(plan: plan, scenario: scenario, displayScale: displayScale)
    prepared.draw()
    return prepared.byteCount
}

/// Measures every standard workload with calibration excluded and a fixed batch per reported sample.
public func measureDrawBenchmarks(
    iterations: Int,
    targetNanoseconds: UInt64 = 400_000_000
) throws -> DrawBenchmarkReport {
    precondition(iterations >= 2)
    precondition(targetNanoseconds > 0)
    var results: [DrawBenchmarkMeasurements] = []
    for grid in DrawBenchmarkGrid.standard {
        guard let plan = makeBtopShapedPlan(for: grid) else { throw DrawBenchmarkError.invalidTerminal }
        for scenario in DrawBenchmarkScenario.allCases {
            let prepared = try PreparedDraw(plan: plan, scenario: scenario, displayScale: 2)
            let stable = measureDurationStable(
                iterations: iterations,
                targetNanoseconds: targetNanoseconds,
                measureBatch: { count in
                    let start = DispatchTime.now().uptimeNanoseconds
                    for _ in 0..<count { prepared.draw() }
                    return DispatchTime.now().uptimeNanoseconds - start
                }
            )
            results.append(DrawBenchmarkMeasurements(
                grid: grid,
                scenario: scenario,
                batchCount: stable.batchCount,
                drawDurationNanoseconds: stable.totals.map { $0 / UInt64(stable.batchCount) },
                sampleDurationNanoseconds: stable.totals
            ))
        }
    }
    return DrawBenchmarkReport(measurements: results)
}

private final class PreparedDraw {
    let byteCount: Int
    private let plan: RenderFramePlan
    private let metrics: TerminalRenderMetrics
    private var context: CGContext?
    private let storage: UnsafeMutableRawPointer

    init(plan: RenderFramePlan, scenario: DrawBenchmarkScenario, displayScale: CGFloat) throws {
        guard let metrics = TerminalRenderMetrics(displayScale: displayScale) else {
            throw DrawBenchmarkError.invalidMetrics
        }
        let rows = Set(0..<min(4, plan.rows))
        self.plan = scenario == .fullFrame
            ? plan
            : clipFramePlan(plan, to: TerminalDamage(rows: rows))
        guard let size = renderFrameSize(for: plan, metrics: metrics) else {
            throw DrawBenchmarkError.invalidFrame
        }
        let pixels = size.pixelWidth.multipliedReportingOverflow(by: size.pixelHeight)
        let bytes = pixels.partialValue.multipliedReportingOverflow(by: 4)
        guard pixels.overflow == false, bytes.overflow == false else {
            throw DrawBenchmarkError.invalidFrame
        }
        let storage = UnsafeMutableRawPointer.allocate(
            byteCount: bytes.partialValue,
            alignment: MemoryLayout<UInt32>.alignment
        )
        storage.initializeMemory(as: UInt8.self, repeating: 0, count: bytes.partialValue)
        guard let colorSpace = CGColorSpace(name: CGColorSpace.sRGB),
              let context = CGContext(
                  data: storage,
                  width: size.pixelWidth,
                  height: size.pixelHeight,
                  bitsPerComponent: 8,
                  bytesPerRow: size.pixelWidth * 4,
                  space: colorSpace,
                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
                    | CGBitmapInfo.byteOrder32Big.rawValue
              )
        else {
            storage.deallocate()
            throw DrawBenchmarkError.allocationFailed
        }
        context.translateBy(x: 0, y: CGFloat(size.pixelHeight))
        context.scaleBy(x: displayScale, y: -displayScale)
        if scenario == .damageClipped {
            for row in rows {
                context.addRect(CGRect(
                    x: 0,
                    y: CGFloat(row) * metrics.cellSize.height,
                    width: size.pointSize.width,
                    height: metrics.cellSize.height
                ))
            }
            context.clip()
        }
        self.byteCount = bytes.partialValue
        self.metrics = metrics
        self.context = context
        self.storage = storage
    }

    deinit {
        context = nil
        storage.deallocate()
    }

    func draw() {
        guard let context else { return }
        drawRenderFrame(plan, metrics: metrics, in: context)
    }
}

private func measureDurationStable(
    iterations: Int,
    targetNanoseconds: UInt64,
    measureBatch: (Int) -> UInt64
) -> (batchCount: Int, totals: [UInt64]) {
    var batchCount = 1
    var calibration = measureBatch(batchCount)
    while calibration < targetNanoseconds {
        batchCount = scaledBatchCount(
            current: batchCount,
            observedNanoseconds: calibration,
            targetNanoseconds: targetNanoseconds
        )
        calibration = measureBatch(batchCount)
    }
    while true {
        let totals = (0..<iterations).map { _ in measureBatch(batchCount) }
        if totals.allSatisfy({ $0 >= targetNanoseconds }) {
            return (batchCount, totals)
        }
        batchCount = scaledBatchCount(
            current: batchCount,
            observedNanoseconds: totals.min() ?? 0,
            targetNanoseconds: targetNanoseconds
        )
    }
}

private func scaledBatchCount(
    current: Int,
    observedNanoseconds: UInt64,
    targetNanoseconds: UInt64
) -> Int {
    guard observedNanoseconds > 0 else { return current + 1 }
    let numerator = UInt64(current) * targetNanoseconds
    let scaled = (numerator + observedNanoseconds - 1) / observedNanoseconds
    return max(current + 1, Int(scaled))
}
