// The F3 admission probe for doc 31: does admitting a scrolled-off row into an open logical
// line cost more than today's pack-one-record-per-display-row admission?
//
// Two arms, one process, interleaved ABBA. **Baseline** reproduces
// `Terminal.swift#appendToScrollback`: `PackedRetainedRow.pack` per display row, an append into
// the retained buffer, and the two accumulations that call site performs (charged bytes and
// stored cells). **Candidate** is doc 31's open-line rule with `F4`'s corrected semantics: the
// row's cells are appended to the arena's open record at the write cursor, `.spacerHead` cells
// are dropped (the store never held one), a row that is not soft-wrapped closes the record and
// writes its header bits, and mutation only ever touches the tail. Both arms admit the *same*
// engine-produced rows, and a readback outside every timed region proves they hold the same
// display rows cell for cell.
//
// Belongs here: the two admitters, the four content classes, and the calibration and gates that
// decide whether a run may be quoted. Does not belong here: a threshold or a verdict (those are
// `31/D1`'s Part B rule for F3, frozen at `d6c83b0` before this file existed), the read walk
// (`TerminalLogicalLineReadProbe.swift` owns it), or the counting pass
// (`TerminalLogicalLineIndexProbe.swift` owns it).
//
// **Nothing in F1's or F2's files is edited by this finding.** What is reused from them is the
// harness they already own -- `RetainedStimulus`, `interleavedRounds`, `ArmRound`, `median`,
// `percentile`, `logicalLines`, `probeKind`, `loadAverageDescription`. What is *not* reused is
// `buildStimulus`: F3 needs two content classes F1's frozen `LogicalLineContentClass` does not
// have, and adding a case to that enum would change `allCases` and so change what F1's own
// measurement runs. The stimulus builder below is therefore F3's own, and it stores rows
// materialized to full width because that is the shape production admission actually receives
// from the live grid -- `pack`'s first walk covers every column, and charging the baseline a
// shorter walk than production pays would understate it.
//
// Not part of the `just test` gate. Every measurement is skipped unless
// `DANTERM_LOGICAL_LINE_PROBE` is set. Run it as:
//
//     DANTERM_LOGICAL_LINE_PROBE=1 swift test -c release --package-path lib/TerminalCore \
//       --filter TerminalLogicalLineAdmissionProbe
//
// Release matters: the bound in `31/D1`'s F3 rule is derived from release-build shares.
import Foundation
import Testing

@testable import TerminalCore

// MARK: - Content classes

/// The four stimulus shapes `31/D1`'s F3 rule froze.
///
/// `mix` and `full` are Part A's two classes, generated by F1's own `logicalLines(for:count:)`
/// so the campaign's three probes measure one content model. `stream` is new to F3 and is the
/// class closest to `H3`'s named falsifier: `28/F20` Observation 5 measured what
/// `benchmark/scrollback-stream` actually retains -- CRLF-terminated rows of ~59 dense cells
/// that never soft-wrap -- which is the *worst* case for the candidate's "fewer records"
/// mechanism, since one record is created per display row exactly as today. `wide` carries no
/// verdict: the rule's bound is derived from an ASCII workload, so wide content is measured as
/// an observation beside it rather than inside it.
enum AdmissionContentClass: String, CaseIterable {
    case mix
    case full
    case stream
    case wide

    /// Whether `31/D1`'s F3 thresholds are read against this class at all.
    var isVerdictBearing: Bool { self != .wide }
}

/// The logical lines a class is made of, before the engine wraps them.
///
/// `mix` and `full` delegate to F1's generator rather than restating it. `stream` reproduces
/// `benchmarks/fixtures/terminal-app.json`'s `scrollback-stream` template verbatim, which is
/// what makes its ~59-cell calibration a reproduction rather than a target. `wide` is CJK, with
/// lengths chosen so most lines exceed 89 clusters and therefore meet the one-column gap that
/// makes the engine insert a `.spacerHead` -- the case `F4` Observation 1 turns on.
func admissionLogicalLines(for contentClass: AdmissionContentClass, count: Int) -> [String] {
    switch contentClass {
    case .mix:
        return logicalLines(for: .mix, count: count)
    case .full:
        return logicalLines(for: .full, count: count)
    case .stream:
        return (0..<count).map {
            "DANTERM-SCROLLBACK-\(String(format: "%05d", $0)) sustained plain-text output payload"
        }
    case .wide:
        var random = DeterministicSequence(seed: 0x5EED_31F3)
        let alphabet = Array("界面測試漢字全形文本輸出終端機緩衝區")
        return (0..<count).map { index in
            // 60..219 clusters: past 89 the first display row ends one column short of a
            // 2-cell cluster, which is what forces the spacer.
            let clusters = 60 + random.next(below: 160)
            var line = String()
            line.reserveCapacity(clusters * 3)
            for offset in 0..<clusters {
                line.append(alphabet[(index &* 13 &+ offset &* 5) % alphabet.count])
            }
            return line
        }
    }
}

/// Feeds a real `Terminal` and takes back the display rows it retained, materialized to full
/// width and trimmed to a logical-line boundary.
///
/// Full width, not canonical extent, because production admission is handed a live-grid row:
/// `pack` walks every column and decides the trim itself, and so must the candidate. Caps are
/// raised far above production so the fill stops on the stimulus rather than on a bound, and
/// the two side-table fields are stripped from every cell so neither arm builds a table the
/// other does not -- the same strip Part A made, and conservative toward the baseline for the
/// same reason (under the candidate an identity run table would be built once per logical line
/// instead of once per display row).
func buildAdmissionStimulus(
    contentClass: AdmissionContentClass,
    targetDisplayRows: Int,
    columns: Int = 179,
    rows: Int = 66
) -> RetainedStimulus {
    var terminal = Terminal(
        columns: columns,
        rows: rows,
        scrollbackBudgetBytes: 1 << 28
    )!

    var fed = 0
    let lines = admissionLogicalLines(for: contentClass, count: 60_000)
    while terminal.scrollbackRowCount < targetDisplayRows + rows, fed < lines.count {
        terminal.feed(Array("\(lines[fed])\r\n".utf8))
        fed += 1
    }

    var displayRows: [Terminal.GridRow] = []
    var lineStarts: [Int] = [0]
    var index = 0
    while index < terminal.scrollbackRowCount {
        guard var row = terminal.retainedRowForTesting(at: index) else { break }
        for column in row.cells.indices {
            row.cells[column].hyperlinkId = nil
            row.cells[column].contentIdentity = nil
        }
        displayRows.append(row.materialized(to: columns))
        if row.isSoftWrapped == false { lineStarts.append(displayRows.count) }
        index += 1
        if displayRows.count >= targetDisplayRows, row.isSoftWrapped == false { break }
    }
    if lineStarts.last != displayRows.count {
        displayRows.removeLast(displayRows.count - lineStarts[lineStarts.count - 1])
    }

    return RetainedStimulus(displayRows: displayRows, lineStarts: lineStarts, columns: columns)
}

// MARK: - Baseline arm: today's admission

/// Today's admission path, reproduced: one packed record per display row plus its accounting.
///
/// `Terminal.appendToScrollback`, `Terminal.ScrollbackBuffer` and
/// `Terminal.scrollbackByteCost(of:)` are all `private`, so this reproduces the append, the
/// storage and the byte-cost arithmetic rather than calling them; that substitution is F3's
/// stated fidelity limit, exactly as it was F1's. What it does *not* substitute is the encoder:
/// `PackedRetainedRow.pack` is the production one.
struct RowRecordAdmitter {
    private(set) var rows: [Terminal.PackedRetainedRow] = []
    private(set) var chargedBytes = 0
    private(set) var storedCells = 0

    /// Pre-sized because history in steady state is not growing an array -- it is reusing the
    /// storage eviction freed. Both arms are pre-sized, so growth is excluded from both.
    init(expectedRows: Int) {
        rows.reserveCapacity(expectedRows)
    }

    @inline(__always)
    mutating func admit(_ row: Terminal.GridRow) {
        let packed = Terminal.PackedRetainedRow.pack(row)
        rows.append(packed)
        chargedBytes += Self.byteCost(of: packed)
        storedCells += packed.storedCellCount
    }

    /// `Terminal.swift#scrollbackByteCost(of:)`, transcribed.
    @inline(__always)
    static func byteCost(of row: Terminal.PackedRetainedRow) -> Int {
        var total = MemoryLayout<Terminal.PackedRetainedRow>.stride
            + Terminal.arrayStorageHeaderBytes
            + row.storage.capacity
        if row.spillCount > 0 {
            total += Terminal.arrayStorageHeaderBytes
                + row.spills.capacity * MemoryLayout<[Unicode.Scalar]>.stride
            for spill in row.spills {
                total += Terminal.arrayStorageHeaderBytes
                    + spill.capacity * MemoryLayout<Unicode.Scalar>.stride
            }
        }
        return total
    }

    /// The content this store holds, checksummed exactly as Part A checksums a read.
    ///
    /// Outside every timed region: this is `31/D1`'s F3 gate 1, not a measurement.
    func readBackChecksum() -> (checksum: UInt64, displayRows: Int) {
        var checksum: UInt64 = 5_381
        for row in rows {
            row.forEachKind { column, kind in
                checksum = checksum &* 31 &+ UInt64(column) &+ UInt64(kind.probeCode)
            }
            row.forEachContentCell { column, scalars, styleId in
                checksum = checksum &* 31 &+ UInt64(column) &+ UInt64(styleId)
                checksum = checksum &* 31 &+ UInt64(scalars.count)
                if scalars.count > 0 { checksum = checksum &+ UInt64(scalars[0].value) }
            }
        }
        return (checksum, rows.count)
    }

    /// The per-round product `31/D1`'s F3 gate 2 cross-checks. Folded rather than compared
    /// field by field so one value travels with `ArmRound`.
    var product: UInt64 {
        var value: UInt64 = 1_469_598_103_934_665_603
        for term in [UInt64(rows.count), UInt64(chargedBytes), UInt64(storedCells)] {
            value = (value ^ term) &* 1_099_511_628_211
        }
        return value
    }
}

// MARK: - Candidate arm: the open-line rule

/// Doc 31's admission path, prototyped: cells appended to an open logical-line record in one
/// contiguous arena, closed on a hard newline.
///
/// Record layout is F1's, so the campaign's three probes agree on one format:
///
///     bytes 0..3   cell count (UInt32)
///     byte  4      flags -- bit 0 hasWideCells, bit 1 forcedSplit, bits 2..4 semantic prompt
///     bytes 5..7   spare
///     bytes 8..    cell count x the C1 8-byte cell word, verbatim from `PackedRetainedRow`
///
/// Three properties of `F4` are load-bearing here and are why this is not F1's builder with a
/// different entry point. **Tail-only mutation** (`F4` Observation 5): the only record this ever
/// writes is the open one at the write cursor, so an append is a store at a cursor rather than
/// an edit of anything already admitted. **The spacer is never stored** (`F4` case 10): a
/// `.spacerHead` is dropped on the way in and re-derived on the way out, which `readBackChecksum`
/// is held to. **The header bits are content, not width** (`F4` `DD3`/`DD4`): `hasWideCells` is
/// set from the cells in hand, and `forcedSplit` from the 65,536-cell cap.
///
/// One thing this deliberately does *not* do: derive a record's display-row count. Admission
/// knows how many rows it consumed, so the block total is *counted*. `ceil((cells + spacers) /
/// width)` and its wide-cell scan belong to the width-change path, which is `F2`'s.
struct OpenLineAdmitter {
    private var arena: [UInt8]
    private var writeCursor = 0
    private var lineOffsets: [Int] = []
    /// Display rows per block at the admitting width -- the design's only width-dependent state.
    private var blockTotals: [Int] = []

    private var openStart = -1
    private var openCells = 0
    private var openRows = 0
    private var openHasWide = false

    private let width: Int
    private let blockSize = 256

    private static let headerBytes = 8
    private static let cellBytes = 8
    private static let hasWideBit: UInt8 = 0x01
    private static let forcedSplitBit: UInt8 = 0x02
    /// `DD3`: no record exceeds 1/32 of the byte budget, which at 8 bytes a cell is 65,536.
    private static let forcedSplitCells = 65_536

    var recordCount: Int { lineOffsets.count }
    var arenaByteCount: Int { writeCursor }
    var displayRowTotal: Int { blockTotals.reduce(0, +) }

    /// Allocated once at the size the stimulus needs, standing in for the design's fixed byte
    /// ring: the byte budget *is* the arena, so admission never grows it.
    init(arenaBytes: Int, width: Int, expectedRecords: Int) {
        arena = [UInt8](repeating: 0, count: arenaBytes)
        self.width = width
        lineOffsets.reserveCapacity(expectedRecords)
        blockTotals.reserveCapacity(expectedRecords / blockSize + 2)
    }

    /// Admits one scrolled-off display row into the open logical line.
    @inline(__always)
    mutating func admit(_ row: Terminal.GridRow) {
        if openStart < 0 {
            openStart = writeCursor
            writeCursor += Self.headerBytes
            openCells = 0
            openRows = 0
            openHasWide = false
        }

        let base = writeCursor
        var out = 0
        var lastWritten = 0
        var hasWide = false

        row.cells.withUnsafeBufferPointer { cells in
            arena.withUnsafeMutableBufferPointer { bytes in
                for column in 0..<cells.count {
                    let kind = cells[column].kind
                    // The store never held a spacer: it is a wrap artifact of one width.
                    if kind == .spacerHead { continue }
                    if kind == .wideHead { hasWide = true }

                    var word = UInt64(kind.probeCode) << 21
                    word |= UInt64(cells[column].styleId) << 32
                    let scalarCount = cells[column].scalars.count
                    if scalarCount == 1 {
                        word |= UInt64(cells[column].scalars[0].value)
                    } else if scalarCount > 1 {
                        fatalError("probe stimulus produced a multi-scalar cell; arena has no spill table")
                    }
                    // A never-written cell encodes to a zero word and the arena is already
                    // zero, so the cheapest way to write it is not to -- the same omission
                    // `PackedRetainedRow.pack` makes, kept so the arms write the same bytes.
                    if word != 0 {
                        let at = base + out * Self.cellBytes
                        for byte in 0..<Self.cellBytes {
                            bytes[at + byte] = UInt8(truncatingIfNeeded: word >> (8 * byte))
                        }
                        lastWritten = out
                    }
                    out += 1
                }
            }
        }

        // A soft-wrapped row is measured to full width, a hard-ended row to its canonical
        // extent -- `Terminal.swift#reconstructLogicalLines`'s own rule (`F4` case 17).
        let extent = row.isSoftWrapped ? out : min(max(lastWritten + 1, 1), out)
        writeCursor = base + extent * Self.cellBytes
        openCells += extent
        openRows += 1
        openHasWide = openHasWide || hasWide

        if row.isSoftWrapped == false || openCells >= Self.forcedSplitCells {
            close(forced: row.isSoftWrapped)
        }
    }

    /// Writes the open record's header and publishes it to the index.
    @inline(__always)
    private mutating func close(forced: Bool) {
        let count = UInt32(openCells)
        arena.withUnsafeMutableBufferPointer { bytes in
            for byte in 0..<4 {
                bytes[openStart + byte] = UInt8(truncatingIfNeeded: count >> (8 * UInt32(byte)))
            }
            var flags: UInt8 = 0
            if openHasWide { flags |= Self.hasWideBit }
            if forced { flags |= Self.forcedSplitBit }
            bytes[openStart + 4] = flags
        }
        lineOffsets.append(openStart)
        let block = (lineOffsets.count - 1) / blockSize
        while blockTotals.count <= block { blockTotals.append(0) }
        blockTotals[block] += openRows
        openStart = -1
    }

    /// Closes a trailing open record. Called after admission, outside the timed region: the
    /// stimulus ends on a logical-line boundary, so this is a no-op that exists to say so.
    mutating func finish() {
        if openStart >= 0 { close(forced: false) }
    }

    /// Re-derives the display rows this arena holds, and checksums them exactly as the baseline
    /// checksums its own -- which is `31/D1`'s F3 gate 1.
    ///
    /// The spacer the admission path dropped is re-inserted here, at read, from (record cells,
    /// width) alone: a 2-cell cluster meeting a one-column gap does not split, so the gap takes
    /// a `.spacerHead` carrying the head's style and the cluster starts the next row
    /// (`F4` Observation 1, `Terminal.swift#pack`). If that derivation is wrong the checksums
    /// diverge and the run is void, which is the point.
    func readBackChecksum() -> (checksum: UInt64, displayRows: Int) {
        var checksum: UInt64 = 5_381
        var displayRows = 0
        var kinds: [UInt8] = []
        var fields: [UInt32] = []
        var styles: [UInt32] = []
        kinds.reserveCapacity(width)
        fields.reserveCapacity(width)
        styles.reserveCapacity(width)

        func flush() {
            for column in kinds.indices {
                checksum = checksum &* 31 &+ UInt64(column) &+ UInt64(kinds[column])
            }
            for column in fields.indices {
                checksum = checksum &* 31 &+ UInt64(column) &+ UInt64(styles[column])
                let scalarCount: UInt64 = fields[column] == 0 ? 0 : 1
                checksum = checksum &* 31 &+ scalarCount
                if scalarCount > 0 { checksum = checksum &+ UInt64(fields[column]) }
            }
            displayRows += 1
            kinds.removeAll(keepingCapacity: true)
            fields.removeAll(keepingCapacity: true)
            styles.removeAll(keepingCapacity: true)
        }

        for offset in lineOffsets {
            let cellCount = Int(UInt32(arena[offset])
                | (UInt32(arena[offset + 1]) << 8)
                | (UInt32(arena[offset + 2]) << 16)
                | (UInt32(arena[offset + 3]) << 24))
            let base = offset + Self.headerBytes
            var column = 0
            for index in 0..<cellCount {
                var word: UInt64 = 0
                let at = base + index * Self.cellBytes
                for byte in 0..<Self.cellBytes { word |= UInt64(arena[at + byte]) << (8 * byte) }
                let kind = UInt8((word >> 21) & 0x7)
                let styleId = UInt32(truncatingIfNeeded: word >> 32)

                if kind == TerminalCellKind.wideHead.probeCode, column == width - 1 {
                    kinds.append(TerminalCellKind.spacerHead.probeCode)
                    fields.append(0)
                    styles.append(styleId)
                    flush()
                    column = 0
                }

                kinds.append(kind)
                fields.append(UInt32(word & 0x1F_FFFF))
                styles.append(styleId)
                column += 1
                if column == width, index + 1 < cellCount {
                    flush()
                    column = 0
                }
            }
            if kinds.isEmpty == false { flush() }
        }
        return (checksum, displayRows)
    }

    /// The per-round product `31/D1`'s F3 gate 2 cross-checks, folded like the baseline's.
    var product: UInt64 {
        var value: UInt64 = 1_469_598_103_934_665_603
        for term in [UInt64(recordCount), UInt64(arenaByteCount), UInt64(displayRowTotal)] {
            value = (value ^ term) &* 1_099_511_628_211
        }
        return value
    }
}

// MARK: - The probe

/// This file's own clock. F1's and F2's are `private` to their files, and each probe owning one
/// is what keeps a timing change in one from silently reaching another.
private func now() -> UInt64 { DispatchTime.now().uptimeNanoseconds }

/// `31/F3`: prices admission on both arms, at four content classes.
///
/// Reports distributions and gate outcomes; it prints no verdict. The thresholds live in
/// `31/D1`'s Part B rule for F3 and are applied once, by hand, to what this prints.
@Suite(.serialized)
struct TerminalLogicalLineAdmissionProbe {
    static let probeIsEnabled = ProcessInfo.processInfo.environment["DANTERM_LOGICAL_LINE_PROBE"] != nil
    static let targetDisplayRows = 10_000
    static let rounds = 5
    static let warmupRounds = 2

    @Test("F3 calibration: what each class admits, and how its wraps are distributed", .enabled(if: probeIsEnabled))
    func admissionCalibration() throws {
        for contentClass in AdmissionContentClass.allCases {
            let stimulus = buildAdmissionStimulus(
                contentClass: contentClass, targetDisplayRows: Self.targetDisplayRows
            )
            let counts = stimulus.storedCellCounts()
            let sorted = counts.sorted()
            let softWrapped = stimulus.displayRows.filter { $0.isSoftWrapped }.count
            let spacers = stimulus.displayRows.reduce(0) { total, row in
                total + row.cells.filter { $0.kind == .spacerHead }.count
            }
            let wideRows = stimulus.displayRows.filter { row in
                row.cells.contains { $0.kind == .wideHead }
            }.count
            print(
                """
                [F3 calibration] class=\(contentClass.rawValue) displayRows=\(counts.count) \
                logicalLines=\(stimulus.lineCount) \
                rowsPerLine=\(String(format: "%.2f", Double(counts.count) / Double(stimulus.lineCount))) \
                softWrappedFraction=\(String(format: "%.3f", Double(softWrapped) / Double(counts.count))) \
                spacerHeads=\(spacers) wideRows=\(wideRows) \
                medianCells=\(sorted[sorted.count / 2]) p95Cells=\(percentile(counts, 0.95)) \
                meanCells=\(String(format: "%.1f", Double(counts.reduce(0, +)) / Double(counts.count))) \
                minCells=\(sorted.first ?? 0) maxCells=\(sorted.last ?? 0)
                """
            )
            #expect(counts.count >= 9_000)
        }
    }

    @Test("F3: open-line append vs today's row-record admission", .enabled(if: probeIsEnabled))
    func admissionComparison() throws {
        print("[F3] load average before: \(loadAverageDescription())")

        for contentClass in AdmissionContentClass.allCases {
            let stimulus = buildAdmissionStimulus(
                contentClass: contentClass, targetDisplayRows: Self.targetDisplayRows
            )
            let sourceRows = stimulus.displayRows
            let rowCount = sourceRows.count
            let lineCount = stimulus.lineCount
            let storedCells = stimulus.storedCellCounts().reduce(0, +)
            // Sized from the stimulus plus slack; the design's arena is the byte budget, and
            // what matters here is only that admission never grows it.
            let arenaBytes = (storedCells + 8 * lineCount) * 8 + 1 << 20

            func baselineArm() -> ArmRound {
                var store = RowRecordAdmitter(expectedRows: rowCount)
                let started = now()
                for row in sourceRows { store.admit(row) }
                let elapsed = now() &- started
                return ArmRound(nanoseconds: elapsed, readCount: rowCount, checksum: store.product)
            }

            func candidateArm() -> ArmRound {
                var store = OpenLineAdmitter(
                    arenaBytes: arenaBytes, width: stimulus.columns, expectedRecords: lineCount
                )
                let started = now()
                for row in sourceRows { store.admit(row) }
                let elapsed = now() &- started
                store.finish()
                return ArmRound(nanoseconds: elapsed, readCount: rowCount, checksum: store.product)
            }

            // Gate 1: both stores are read back and must hold the same display rows, cell for
            // cell. Built and checked outside every timed region.
            var baselineStore = RowRecordAdmitter(expectedRows: rowCount)
            var candidateStore = OpenLineAdmitter(
                arenaBytes: arenaBytes, width: stimulus.columns, expectedRecords: lineCount
            )
            for row in sourceRows {
                baselineStore.admit(row)
                candidateStore.admit(row)
            }
            candidateStore.finish()
            let baselineRead = baselineStore.readBackChecksum()
            let candidateRead = candidateStore.readBackChecksum()

            print(
                """
                [F3 \(contentClass.rawValue)/stores] displayRows=\(rowCount) logicalLines=\(lineCount) \
                storedCells=\(storedCells) \
                baseline: records=\(baselineStore.rows.count) chargedBytes=\(baselineStore.chargedBytes) \
                storedCells=\(baselineStore.storedCells) | \
                candidate: records=\(candidateStore.recordCount) arenaBytes=\(candidateStore.arenaByteCount) \
                countedRows=\(candidateStore.displayRowTotal)
                  readback baselineRows=\(baselineRead.displayRows) candidateRows=\(candidateRead.displayRows) \
                checksumsEqual=\(baselineRead.checksum == candidateRead.checksum)
                """
            )
            #expect(baselineRead.checksum == candidateRead.checksum)
            #expect(baselineRead.displayRows == candidateRead.displayRows)
            #expect(candidateStore.displayRowTotal == rowCount)
            #expect(candidateStore.recordCount == lineCount)

            let expectedBaselineProduct = baselineStore.product
            let expectedCandidateProduct = candidateStore.product

            let measured = interleavedRounds(
                rounds: Self.rounds, warmupRounds: Self.warmupRounds,
                armA: baselineArm, armB: candidateArm
            )
            let aa = interleavedRounds(
                rounds: Self.rounds, warmupRounds: Self.warmupRounds,
                armA: baselineArm, armB: baselineArm
            )

            let baselineMedian = median(measured.a)
            let candidateMedian = median(measured.b)
            let aaLeft = median(aa.a)
            let aaRight = median(aa.b)

            print(
                """
                [F3 \(contentClass.rawValue)] admittedRows=\(measured.readCount) rounds=\(Self.rounds) \
                verdictBearing=\(contentClass.isVerdictBearing)
                  baseline  median=\(String(format: "%.1f", baselineMedian)) ns/row \
                (min \(String(format: "%.1f", measured.a.min() ?? .nan)), \
                max \(String(format: "%.1f", measured.a.max() ?? .nan)))
                  candidate median=\(String(format: "%.1f", candidateMedian)) ns/row \
                (min \(String(format: "%.1f", measured.b.min() ?? .nan)), \
                max \(String(format: "%.1f", measured.b.max() ?? .nan)))
                  ratio=\(String(format: "%.3f", candidateMedian / baselineMedian))x \
                delta=\(String(format: "%+.2f", (candidateMedian / baselineMedian - 1) * 100))%
                  per logical line: baseline=\(String(format: "%.1f", baselineMedian * Double(rowCount) / Double(lineCount))) ns \
                candidate=\(String(format: "%.1f", candidateMedian * Double(rowCount) / Double(lineCount))) ns
                  A/A control ratio=\(String(format: "%.3f", aaRight / aaLeft))x \
                delta=\(String(format: "%+.2f", (aaRight / aaLeft - 1) * 100))% (resolution floor)
                  products baselineExpected=\(expectedBaselineProduct) measured=\(measured.checksumA) \
                candidateExpected=\(expectedCandidateProduct) measured=\(measured.checksumB)
                """
            )
            // Gate 2, non-elision: each arm's per-round product must equal the one computed
            // outside the timed region, and neither may be the empty store's.
            #expect(measured.checksumA == expectedBaselineProduct)
            #expect(measured.checksumB == expectedCandidateProduct)
            #expect(measured.readCount == rowCount)
        }

        print("[F3] load average after: \(loadAverageDescription())")
    }

    /// Descriptive, outside `31/D1`'s F3 rule: where the baseline's per-row cost sits.
    ///
    /// The leading deflation of any candidate margin is that it is the per-row heap allocation
    /// alone, and so recoverable without a redesign. This splits today's admission into encode,
    /// encode+append, and the whole path, so the margin can be attributed rather than assumed.
    @Test("F3 supplementary: how today's admission splits into encode, append and accounting", .enabled(if: probeIsEnabled))
    func baselineDecomposition() throws {
        for contentClass in AdmissionContentClass.allCases {
            let stimulus = buildAdmissionStimulus(
                contentClass: contentClass, targetDisplayRows: Self.targetDisplayRows
            )
            let sourceRows = stimulus.displayRows
            let rowCount = sourceRows.count

            func timed(_ body: () -> Int) -> Double {
                for _ in 0..<Self.warmupRounds { _ = body() }
                var samples: [Double] = []
                for _ in 0..<Self.rounds {
                    let started = now()
                    let sink = body()
                    let elapsed = now() &- started
                    #expect(sink > 0)
                    samples.append(Double(elapsed) / Double(rowCount))
                }
                return median(samples)
            }

            let packOnly = timed {
                var cells = 0
                for row in sourceRows { cells &+= Terminal.PackedRetainedRow.pack(row).storedCellCount }
                return cells
            }
            let packAndAppend = timed {
                var store: [Terminal.PackedRetainedRow] = []
                store.reserveCapacity(rowCount)
                for row in sourceRows { store.append(Terminal.PackedRetainedRow.pack(row)) }
                return store.count
            }
            let whole = timed {
                var store = RowRecordAdmitter(expectedRows: rowCount)
                for row in sourceRows { store.admit(row) }
                return store.rows.count
            }
            print(
                """
                [F3 decomposition \(contentClass.rawValue)] rows=\(rowCount) rounds=\(Self.rounds) \
                packOnly=\(String(format: "%.1f", packOnly)) ns/row \
                packAndAppend=\(String(format: "%.1f", packAndAppend)) ns/row \
                whole=\(String(format: "%.1f", whole)) ns/row
                """
            )
        }
    }
}
