// Generated by scripts/generate-terminal-capability-projection.py; do not edit.
// Projected from docs/terminal-capabilities.md, which is the authored contract.
//
// This file exists so XTGETTCAP answers from the published contract rather than
// from a second list inside the engine. Editing it by hand makes the engine
// promise something the contract never did, which is why the generator's --check
// mode is a gate step.

/// The capability values XTGETTCAP answers with, keyed by the names each answers to.
///
/// A value is the exact byte string a reply carries. An empty value means a boolean
/// capability, whose reply is the requested name with no `=` and no value.
enum TerminalCapabilityProjection {
    static let values: [String: String] = [
        "am": "",
        "bce": "",
        "colors": "256",
        "Co": "256",
        "clear": "\u{1B}[H\u{1B}[2J",
        "cup": "\\E[%i%p1%d;%p2%dH",
        "civis": "\u{1B}[?25l",
        "cnorm": "\u{1B}[?12l\u{1B}[?25h",
        "smcup": "\u{1B}[?1049h",
        "rmcup": "\u{1B}[?1049l",
        "setaf": "\\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m",
        "setab": "\\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m",
        "sgr0": "\u{1B}(B\u{1B}[m",
        "bold": "\u{1B}[1m",
        "smul": "\u{1B}[4m",
        "rmul": "\u{1B}[24m",
        "el": "\u{1B}[K",
        "ed": "\u{1B}[J",
        "kcuu1": "\u{1B}OA",
        "kcud1": "\u{1B}OB",
        "kcub1": "\u{1B}OD",
        "kcuf1": "\u{1B}OC",
        "khome": "\u{1B}OH",
        "kend": "\u{1B}OF",
        "kdch1": "\u{1B}[3~",
        "kpp": "\u{1B}[5~",
        "knp": "\u{1B}[6~",
        "kmous": "\u{1B}[M",
        "TN": "xterm-256color",
        "name": "xterm-256color",
    ]
}
