#!/usr/bin/env python3
"""Generate TerminalCore's pinned Unicode width and test-reference tables."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import urllib.request


UNICODE_VERSION = "17.0.0"
FILES = {
    "EastAsianWidth.txt": (
        f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/EastAsianWidth.txt",
        "ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33",
    ),
    "UnicodeData.txt": (
        f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/UnicodeData.txt",
        "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c",
    ),
    "emoji-data.txt": (
        f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/emoji/emoji-data.txt",
        "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b",
    ),
}
MAX_SCALAR = 0x10FFFF


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-dir",
        type=Path,
        help="read already-downloaded Unicode files from this directory",
    )
    return parser.parse_args()


def verified_data(data_dir: Path | None) -> dict[str, str]:
    contents: dict[str, str] = {}
    for name, (url, expected_hash) in FILES.items():
        if data_dir is None:
            with urllib.request.urlopen(url) as response:
                data = response.read()
        else:
            data = (data_dir / name).read_bytes()
        actual_hash = hashlib.sha256(data).hexdigest()
        if actual_hash != expected_hash:
            raise RuntimeError(f"{name}: expected sha256 {expected_hash}, got {actual_hash}")
        contents[name] = data.decode("utf-8")
    return contents


def parse_codepoint_range(value: str) -> tuple[int, int]:
    parts = value.strip().split("..")
    lower = int(parts[0], 16)
    upper = int(parts[-1], 16)
    return lower, upper


def merge_ranges(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    merged: list[tuple[int, int]] = []
    for lower, upper in sorted(ranges):
        if merged and lower <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(upper, merged[-1][1]))
        else:
            merged.append((lower, upper))
    return merged


def parse_zero_width_ranges(text: str) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    pending: tuple[int, str] | None = None
    for line in text.splitlines():
        fields = line.split(";")
        codepoint = int(fields[0], 16)
        name = fields[1]
        category = fields[2]
        if name.endswith(", First>"):
            pending = (codepoint, category)
        elif name.endswith(", Last>"):
            if pending is None or pending[1] != category:
                raise RuntimeError(f"unmatched UnicodeData range ending at {fields[0]}")
            if category in {"Mn", "Me", "Cf"}:
                result.append((pending[0], codepoint))
            pending = None
        elif category in {"Mn", "Me", "Cf"}:
            result.append((codepoint, codepoint))
    if pending is not None:
        raise RuntimeError("unterminated UnicodeData range")
    return merge_ranges(result)


def parse_property_ranges(text: str, accepted: set[str]) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        codepoints, property_name = (part.strip() for part in line.split(";", 1))
        if property_name in accepted:
            result.append(parse_codepoint_range(codepoints))
    return merge_ranges(result)


def boundary_array(ranges: list[tuple[int, int]]) -> str:
    values = [value for item in ranges for value in item]
    lines = []
    for index in range(0, len(values), 8):
        chunk = ", ".join(f"0x{value:X}" for value in values[index : index + 8])
        lines.append(f"        {chunk},")
    return "\n".join(lines)


def production_source(
    zero_width: list[tuple[int, int]],
    wide: list[tuple[int, int]],
    pictographic: list[tuple[int, int]],
) -> str:
    hashes = ", ".join(f"{name} {digest}" for name, (_, digest) in FILES.items())
    return f'''// Generated by scripts/generate-terminal-unicode-tables.py; do not edit.
// Unicode {UNICODE_VERSION}; source sha256: {hashes}

let terminalUnicodeVersion = "{UNICODE_VERSION}"

/// Protocol widths used by the grid without consulting toolchain Unicode properties.
enum TerminalCellWidth: UInt8, Equatable, Sendable {{
    case zero = 0
    case narrow = 1
    case wide = 2
}}

/// Pinned scalar properties needed to form this slice's terminal cells.
struct TerminalUnicodeProperties: Equatable, Sendable {{
    let cellWidth: TerminalCellWidth
    let isExtendedPictographic: Bool
}}

/// Classifies a scalar using the generated Unicode {UNICODE_VERSION} tables.
func terminalUnicodeProperties(for scalar: Unicode.Scalar) -> TerminalUnicodeProperties {{
    let value = scalar.value
    let width: TerminalCellWidth
    if GeneratedUnicodeTables.contains(value, in: GeneratedUnicodeTables.zeroWidth) {{
        width = .zero
    }} else if GeneratedUnicodeTables.contains(value, in: GeneratedUnicodeTables.wide) {{
        width = .wide
    }} else {{
        width = .narrow
    }}
    return TerminalUnicodeProperties(
        cellWidth: width,
        isExtendedPictographic: GeneratedUnicodeTables.contains(
            value,
            in: GeneratedUnicodeTables.extendedPictographic
        )
    )
}}

/// Generated range boundaries kept private so storage can change without API impact.
private enum GeneratedUnicodeTables {{
    static let zeroWidth: [UInt32] = [
{boundary_array(zero_width)}
    ]

    static let wide: [UInt32] = [
{boundary_array(wide)}
    ]

    static let extendedPictographic: [UInt32] = [
{boundary_array(pictographic)}
    ]

    static func contains(_ value: UInt32, in boundaries: [UInt32]) -> Bool {{
        var lower = 0
        var upper = boundaries.count / 2
        while lower < upper {{
            let middle = lower + (upper - lower) / 2
            let start = boundaries[middle * 2]
            let end = boundaries[middle * 2 + 1]
            if value < start {{
                upper = middle
            }} else if value > end {{
                lower = middle + 1
            }} else {{
                return true
            }}
        }}
        return false
    }}
}}
'''


def reference_ranges(
    zero_width: list[tuple[int, int]],
    wide: list[tuple[int, int]],
    pictographic: list[tuple[int, int]],
) -> list[tuple[int, int, int, bool]]:
    widths = bytearray([1]) * (MAX_SCALAR + 1)
    pictographs = bytearray(MAX_SCALAR + 1)
    for lower, upper in wide:
        widths[lower : upper + 1] = bytes([2]) * (upper - lower + 1)
    for lower, upper in zero_width:
        widths[lower : upper + 1] = bytes([0]) * (upper - lower + 1)
    for lower, upper in pictographic:
        pictographs[lower : upper + 1] = bytes([1]) * (upper - lower + 1)

    result: list[tuple[int, int, int, bool]] = []
    start = 0
    prior = (widths[0], bool(pictographs[0]))
    for value in range(1, MAX_SCALAR + 1):
        current = (widths[value], bool(pictographs[value]))
        if current != prior:
            result.append((start, value - 1, prior[0], prior[1]))
            start = value
            prior = current
    result.append((start, MAX_SCALAR, prior[0], prior[1]))
    return result


def reference_source(ranges: list[tuple[int, int, int, bool]]) -> str:
    entries = "\n".join(
        f"    UnicodeReferenceRange(lowerBound: 0x{lower:X}, upperBound: 0x{upper:X}, "
        f"cellWidth: {width}, isExtendedPictographic: {str(pictographic).lower()}),"
        for lower, upper, width, pictographic in ranges
    )
    return f'''// Generated independently from the official Unicode {UNICODE_VERSION} property files.

/// Exhaustive expected-property run used to validate every Unicode scalar offline.
struct UnicodeReferenceRange {{
    let lowerBound: UInt32
    let upperBound: UInt32
    let cellWidth: UInt8
    let isExtendedPictographic: Bool
}}

let unicodeReferenceRanges: [UnicodeReferenceRange] = [
{entries}
]
'''


def main() -> None:
    args = parse_args()
    data = verified_data(args.data_dir)
    zero_width = parse_zero_width_ranges(data["UnicodeData.txt"])
    wide = parse_property_ranges(data["EastAsianWidth.txt"], {"W", "F"})
    pictographic = parse_property_ranges(data["emoji-data.txt"], {"Extended_Pictographic"})

    repo_root = Path(__file__).resolve().parents[1]
    production = repo_root / "lib/TerminalCore/Sources/TerminalCore/UnicodeProperties.generated.swift"
    reference = repo_root / "lib/TerminalCore/Tests/TerminalCoreTests/UnicodeReference.generated.swift"
    production.write_text(production_source(zero_width, wide, pictographic), encoding="utf-8")
    reference.write_text(
        reference_source(reference_ranges(zero_width, wide, pictographic)),
        encoding="utf-8",
    )
    print(f"generated {production.relative_to(repo_root)}")
    print(f"generated {reference.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
