#!/usr/bin/env python3
"""Compare two draw-path revisions headlessly by interleaving them in one process.

`just benchmark-headless-draw` runs this. It builds each arm as a dynamic library from its
own TerminalCore checkout, loads both into this process, and alternates their batches ABBA so
that machine drift -- which moves every measurement in a process together -- cancels in the
paired difference.

Why it exists: the GUI paired benchmark cannot resolve a 3% change on `incremental-mixed`
any more. macOS lowers the app's CPU clock during a block because the optimized main thread
is ~96% idle, and no collection-side fix removed it. Batching draws to a 400ms floor keeps
this benchmark's thread ~100% occupied, so the governor never demotes it, and interleaving
two arms cancels what drift remains. Measured paired spread is ~0.7% against the GUI
benchmark's 3.98%. Background, evidence and limits: F14 and F21-F23 in
docs/research/8-benchmark-variance-regression.md.

Scope, deliberately narrow. This measures the cost of DRAWING an already-scoped plan. It
does not see damage *generation* -- which rows `setNeedsDisplay` and AppKit's dirty-rect
coalescing mark -- nor `clipFramePlan`'s own cost, both of which sit outside the timed
region. Those stay with the GUI benchmark.

No decision rule is frozen for this instrument yet, so the report is statistics plus an
optional caller-supplied threshold, never a verdict against a threshold this script invented.
"""
import argparse
import ctypes
import importlib.util
import json
import pathlib
import shutil
import statistics
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
ARM_SOURCE = ROOT / "scripts" / "terminal-headless-draw-arm.swift"
DEFAULT_CORE = ROOT / "lib" / "TerminalCore"
ARTIFACTS = ROOT / ".build" / "terminal-headless-draw"

# Both arms must compile under different Swift module names; see validate_module_names.
BASELINE_MODULE = "DrawArmBaseline"
CANDIDATE_MODULE = "DrawArmCandidate"

# Matches TerminalDrawBenchmarkSupport's floor: a batch this long keeps the thread ~100%
# occupied, which is what stops the platform governor from demoting it mid-measurement.
TARGET_BATCH_NANOSECONDS = 400_000_000

CALIBRATION = importlib.util.spec_from_file_location(
    "terminal_benchmark_calibration",
    ROOT / "scripts" / "terminal-benchmark-calibration.py",
)
CAL = importlib.util.module_from_spec(CALIBRATION)
CALIBRATION.loader.exec_module(CAL)


def validate_module_names(baseline_module, candidate_module):
    """Refuse two arms that would collide in the ObjC runtime's global class table.

    Swift classes register with the ObjC runtime, which dedups by name across images even
    under RTLD_LOCAL. Two arms sharing a module name can both execute one arm's code while
    still reporting plausible-looking numbers, so this is checked rather than trusted.
    """
    if baseline_module == candidate_module:
        raise ValueError(
            "both arms would compile under the module name "
            f"{baseline_module!r}; the ObjC runtime dedups classes by name across images, "
            "so the arms must use different module names"
        )


def arm_manifest(module_name, core_path):
    """Bind one arm's module name to its own TerminalCore checkout."""
    core_path = pathlib.Path(core_path)
    if core_path.name != "TerminalCore":
        raise ValueError(
            f"core checkout {str(core_path)!r} must keep the basename 'TerminalCore': "
            "SwiftPM takes a path dependency's identity from the directory name, so a "
            "differently named copy cannot resolve .product(package: \"TerminalCore\")"
        )
    return f'''// swift-tools-version: 6.2
// Generated by scripts/terminal-headless-draw-compare.py -- edits are overwritten.
import PackageDescription

let package = Package(
    name: "{module_name}",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "{module_name}", type: .dynamic, targets: ["{module_name}"]),
    ],
    dependencies: [
        .package(path: "{core_path}"),
    ],
    targets: [
        .target(
            name: "{module_name}",
            dependencies: [
                .product(name: "TerminalCore", package: "TerminalCore"),
                .product(name: "TerminalRenderPlanning", package: "TerminalCore"),
                .product(name: "TerminalRenderExecution", package: "TerminalCore"),
            ],
            path: "Sources/{module_name}",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
'''


def paired_quartets(rounds):
    """Turn ABBA rounds into the two-pair quartets the frozen calibration machinery reads.

    Each round contributes `A1 vs B1` and `B2 vs A2`, pairing every batch with its adjacent
    neighbour so a monotonic drift across the round cancels to first order instead of loading
    onto whichever arm ran first.
    """
    quartets = []
    for index, round_result in enumerate(rounds):
        a_batches = round_result["a"]
        b_batches = round_result["b"]
        if len(a_batches) != 2 or len(b_batches) != 2:
            raise ValueError(f"round {index} must hold two batches per arm")
        if any(value <= 0 for value in list(a_batches) + list(b_batches)):
            raise ValueError(f"round {index} holds a non-positive batch duration")
        quartets.append([
            CAL.symmetric_difference(a_batches[0], b_batches[0]),
            CAL.symmetric_difference(a_batches[1], b_batches[1]),
        ])
    return quartets


def summarize(quartets):
    """Report the paired spread that decides whether a difference is readable at all."""
    values = [value for quartet in quartets for value in quartet]
    if not values:
        raise ValueError("a summary requires at least one paired difference")
    return {
        "quartetCount": len(quartets),
        "pairCount": len(values),
        "pairedMeanPercent": statistics.fmean(values),
        "pairedMedianPercent": statistics.median(values),
        "pairedStandardDeviationPercent": (
            statistics.pstdev(values) if len(values) > 1 else 0.0
        ),
        "pairedValuesPercent": values,
    }


def build_arm(module_name, core_path, workspace):
    """Generate and compile one arm, returning the built dynamic library path."""
    package_root = workspace / module_name
    source_directory = package_root / "Sources" / module_name
    source_directory.mkdir(parents=True, exist_ok=True)
    (package_root / "Package.swift").write_text(
        arm_manifest(module_name, core_path), encoding="utf-8"
    )
    shutil.copyfile(ARM_SOURCE, source_directory / "Arm.swift")
    scratch = workspace / f"{module_name}-build"
    subprocess.run(
        ["swift", "build", "-c", "release", "--scratch-path", str(scratch)],
        cwd=package_root,
        check=True,
        stdout=sys.stderr,
    )
    library = scratch / "release" / f"lib{module_name}.dylib"
    if not library.exists():
        raise FileNotFoundError(f"arm build produced no library at {library}")
    return library


class Arm:
    """One loaded arm, bound to its own dynamic library.

    Loaded RTLD_LOCAL so the two arms cannot resolve each other's symbols; the module-name
    check is what guards the ObjC class table, which RTLD_LOCAL does not cover.
    """

    def __init__(self, library_path):
        self._library = ctypes.CDLL(str(library_path), mode=ctypes.RTLD_LOCAL)
        self._library.arm_prepare.argtypes = [ctypes.c_int32] * 3
        self._library.arm_prepare.restype = ctypes.c_int32
        self._library.arm_batch.argtypes = [ctypes.c_int32]
        self._library.arm_batch.restype = ctypes.c_uint64

    def prepare(self, columns, rows, clip_rows):
        if self._library.arm_prepare(columns, rows, clip_rows) != 0:
            raise RuntimeError("arm failed to prepare its draw surface")

    def batch(self, count):
        return self._library.arm_batch(count)


def calibrate_batch_count(arm, target_nanoseconds=TARGET_BATCH_NANOSECONDS):
    """Grow the batch until one exceeds the occupancy floor."""
    count = 1
    while arm.batch(count) < target_nanoseconds:
        count *= 2
    return count


def run_rounds(baseline, candidate, batch_count, rounds):
    """Alternate the arms ABBA, which is the production schedule shape."""
    results = []
    for _ in range(rounds):
        first_a = baseline.batch(batch_count)
        first_b = candidate.batch(batch_count)
        second_b = candidate.batch(batch_count)
        second_a = baseline.batch(batch_count)
        results.append({"a": [first_a, second_a], "b": [first_b, second_b]})
    return results


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--baseline-core", type=pathlib.Path, default=DEFAULT_CORE,
        help="TerminalCore checkout for the baseline arm (default: this tree)")
    parser.add_argument(
        "--candidate-core", type=pathlib.Path, default=DEFAULT_CORE,
        help="TerminalCore checkout for the candidate arm; defaults to the baseline "
             "checkout, which makes the run an A/A control")
    parser.add_argument("--columns", type=int, default=160)
    parser.add_argument("--rows", type=int, default=50)
    parser.add_argument(
        "--clip-rows", type=int, default=4,
        help="rows of damage to clip to; 0 measures the full frame")
    parser.add_argument("--rounds", type=int, default=8)
    parser.add_argument(
        "--threshold", type=float, default=None,
        help="optional caller-supplied directional threshold in percent. No decision rule "
             "is frozen for this instrument, so omitting this reports statistics only")
    parser.add_argument("--equivalence-band", type=float, default=0.0)
    arguments = parser.parse_args()

    validate_module_names(BASELINE_MODULE, CANDIDATE_MODULE)
    ARTIFACTS.mkdir(parents=True, exist_ok=True)

    baseline_library = build_arm(BASELINE_MODULE, arguments.baseline_core, ARTIFACTS)
    candidate_library = build_arm(CANDIDATE_MODULE, arguments.candidate_core, ARTIFACTS)

    baseline = Arm(baseline_library)
    candidate = Arm(candidate_library)
    for arm in (baseline, candidate):
        arm.prepare(arguments.columns, arguments.rows, arguments.clip_rows)

    batch_count = calibrate_batch_count(baseline)
    rounds = run_rounds(baseline, candidate, batch_count, arguments.rounds)
    quartets = paired_quartets(rounds)

    is_control = (
        pathlib.Path(arguments.baseline_core).resolve()
        == pathlib.Path(arguments.candidate_core).resolve()
    )
    report = {
        "schemaVersion": 1,
        "geometry": {
            "columns": arguments.columns,
            "rows": arguments.rows,
            "clipRows": arguments.clip_rows,
        },
        "batchCount": batch_count,
        "isSelfControl": is_control,
        "baselineCore": str(pathlib.Path(arguments.baseline_core).resolve()),
        "candidateCore": str(pathlib.Path(arguments.candidate_core).resolve()),
        "summary": summarize(quartets),
    }
    if arguments.threshold is not None:
        report["decision"] = CAL.decide(
            [value for quartet in quartets for value in quartet],
            directional_threshold=arguments.threshold,
            equivalence_band=arguments.equivalence_band,
            estimator="median",
        )
        report["decision"]["thresholdSource"] = "caller-supplied; not a frozen rule"
    json.dump(report, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
