#!/usr/bin/env python3
"""Compare two draw-path revisions headlessly by interleaving them in one process.

`just benchmark-headless-draw` runs this. It builds each arm as a dynamic library from its
own TerminalCore checkout, loads both into this process, and alternates their batches ABBA so
that machine drift -- which moves every measurement in a process together -- cancels in the
paired difference.

Why it exists: the GUI paired benchmark cannot resolve a 3% change on `incremental-mixed`
any more. macOS lowers the app's CPU clock during a block because the optimized main thread
is ~96% idle, and no collection-side fix removed it. Batching draws to a 400ms floor keeps
this benchmark's thread ~100% occupied, so the governor never demotes it, and interleaving
two arms cancels what drift remains. Measured paired spread is ~0.7% against the GUI
benchmark's 3.98%. Background, evidence and limits: F14 and F21-F23 in
docs/research/8-benchmark-variance-regression.md.

Scope, deliberately narrow. This measures the cost of DRAWING an already-scoped plan. It
does not see damage *generation* -- which rows `setNeedsDisplay` and AppKit's dirty-rect
coalescing mark -- nor `clipFramePlan`'s own cost, both of which sit outside the timed
region. Those stay with the GUI benchmark.

No decision rule is frozen for this instrument yet, so the report is statistics plus an
optional caller-supplied threshold, never a verdict against a threshold this script invented.
"""
import argparse
import ctypes
import importlib.util
import json
import pathlib
import shutil
import statistics
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
ARM_SOURCE = ROOT / "scripts" / "terminal-headless-draw-arm.swift"
DEFAULT_CORE = ROOT / "lib" / "TerminalCore"
ARTIFACTS = ROOT / ".build" / "terminal-headless-draw"

# Content workloads the arm can fill its grid with. Must match DrawBenchmarkWorkload's raw
# values in TerminalDrawBenchmarkSupport, which the arm's generators are copied from.
WORKLOADS = ("btop-shaped", "text-shaped")

# Both arms must compile under different Swift module names; see validate_module_names.
BASELINE_MODULE = "DrawArmBaseline"
CANDIDATE_MODULE = "DrawArmCandidate"

# Matches TerminalDrawBenchmarkSupport's floor: a batch this long keeps the thread ~100%
# occupied, which is what stops the platform governor from demoting it mid-measurement.
TARGET_BATCH_NANOSECONDS = 400_000_000

CALIBRATION = importlib.util.spec_from_file_location(
    "terminal_benchmark_calibration",
    ROOT / "scripts" / "terminal-benchmark-calibration.py",
)
CAL = importlib.util.module_from_spec(CALIBRATION)
CALIBRATION.loader.exec_module(CAL)


def validate_module_names(baseline_module, candidate_module):
    """Refuse two arms that would collide in the ObjC runtime's global class table.

    Swift classes register with the ObjC runtime, which dedups by name across images even
    under RTLD_LOCAL. Two arms sharing a module name can both execute one arm's code while
    still reporting plausible-looking numbers, so this is checked rather than trusted.
    """
    if baseline_module == candidate_module:
        raise ValueError(
            "both arms would compile under the module name "
            f"{baseline_module!r}; the ObjC runtime dedups classes by name across images, "
            "so the arms must use different module names"
        )


def arm_manifest(module_name, core_path):
    """Bind one arm's module name to its own TerminalCore checkout."""
    core_path = pathlib.Path(core_path)
    if core_path.name != "TerminalCore":
        raise ValueError(
            f"core checkout {str(core_path)!r} must keep the basename 'TerminalCore': "
            "SwiftPM takes a path dependency's identity from the directory name, so a "
            "differently named copy cannot resolve .product(package: \"TerminalCore\")"
        )
    return f'''// swift-tools-version: 6.2
// Generated by scripts/terminal-headless-draw-compare.py -- edits are overwritten.
import PackageDescription

let package = Package(
    name: "{module_name}",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "{module_name}", type: .dynamic, targets: ["{module_name}"]),
    ],
    dependencies: [
        .package(path: "{core_path}"),
    ],
    targets: [
        .target(
            name: "{module_name}",
            dependencies: [
                .product(name: "TerminalCore", package: "TerminalCore"),
                .product(name: "TerminalRenderPlanning", package: "TerminalCore"),
                .product(name: "TerminalRenderExecution", package: "TerminalCore"),
            ],
            path: "Sources/{module_name}",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
'''


def paired_quartets(rounds):
    """Turn ABBA rounds into the two-pair quartets the frozen calibration machinery reads.

    Each round contributes `A1 vs B1` and `B2 vs A2`, pairing every batch with its adjacent
    neighbour so a monotonic drift across the round cancels to first order instead of loading
    onto whichever arm ran first.
    """
    quartets = []
    for index, round_result in enumerate(rounds):
        a_batches = round_result["a"]
        b_batches = round_result["b"]
        if len(a_batches) != 2 or len(b_batches) != 2:
            raise ValueError(f"round {index} must hold two batches per arm")
        if any(value <= 0 for value in list(a_batches) + list(b_batches)):
            raise ValueError(f"round {index} holds a non-positive batch duration")
        quartets.append([
            CAL.symmetric_difference(a_batches[0], b_batches[0]),
            CAL.symmetric_difference(a_batches[1], b_batches[1]),
        ])
    return quartets


def summarize(quartets):
    """Report the paired spread that decides whether a difference is readable at all."""
    values = [value for quartet in quartets for value in quartet]
    if not values:
        raise ValueError("a summary requires at least one paired difference")
    return {
        "quartetCount": len(quartets),
        "pairCount": len(values),
        "pairedMeanPercent": statistics.fmean(values),
        "pairedMedianPercent": statistics.median(values),
        "pairedStandardDeviationPercent": (
            statistics.pstdev(values) if len(values) > 1 else 0.0
        ),
        "pairedValuesPercent": values,
    }


def antisymmetric_estimate(forward_percents, reverse_percents):
    """Split a two-direction measurement into the part that reverses and the part that does not.

    A real difference between two revisions flips sign when the arms swap slots; anything
    that survives the swap -- load order, slot asymmetry -- does not. Reporting the two
    separately is what stops an order bias being published as a performance claim. The first
    positive control read -1.797% one way and +0.101% the other, so this is not hypothetical.
    """
    if not forward_percents or not reverse_percents:
        raise ValueError("an antisymmetric estimate requires both comparison directions")
    forward = statistics.fmean(forward_percents)
    reverse = statistics.fmean(reverse_percents)
    return {
        "realEffectPercent": (forward - reverse) / 2,
        "orderBiasPercent": (forward + reverse) / 2,
        "forwardMeanPercent": forward,
        "reverseMeanPercent": reverse,
    }


def build_arm(module_name, core_path, workspace):
    """Generate and compile one arm, returning the built dynamic library path."""
    package_root = workspace / module_name
    source_directory = package_root / "Sources" / module_name
    source_directory.mkdir(parents=True, exist_ok=True)
    (package_root / "Package.swift").write_text(
        arm_manifest(module_name, core_path), encoding="utf-8"
    )
    shutil.copyfile(ARM_SOURCE, source_directory / "Arm.swift")
    scratch = workspace / f"{module_name}-build"
    subprocess.run(
        ["swift", "build", "-c", "release", "--scratch-path", str(scratch)],
        cwd=package_root,
        check=True,
        stdout=sys.stderr,
    )
    library = scratch / "release" / f"lib{module_name}.dylib"
    if not library.exists():
        raise FileNotFoundError(f"arm build produced no library at {library}")
    return library


class Arm:
    """One loaded arm, bound to its own dynamic library.

    Loaded RTLD_LOCAL so the two arms cannot resolve each other's symbols; the module-name
    check is what guards the ObjC class table, which RTLD_LOCAL does not cover.
    """

    def __init__(self, library_path):
        self._library = ctypes.CDLL(str(library_path), mode=ctypes.RTLD_LOCAL)
        self._library.arm_prepare.argtypes = [ctypes.c_int32] * 4
        self._library.arm_prepare.restype = ctypes.c_int32
        self._library.arm_batch.argtypes = [ctypes.c_int32]
        self._library.arm_batch.restype = ctypes.c_uint64

    def prepare(self, columns, rows, clip_rows, workload):
        text_shaped = 1 if workload == "text-shaped" else 0
        if self._library.arm_prepare(columns, rows, clip_rows, text_shaped) != 0:
            raise RuntimeError("arm failed to prepare its draw surface")

    def batch(self, count):
        return self._library.arm_batch(count)


def calibrate_batch_count(arms, target_nanoseconds=TARGET_BATCH_NANOSECONDS):
    """Pick one batch size that clears the occupancy floor for every arm.

    Calibrating on the baseline arm alone made the batch size depend on comparison
    direction, so swapping the arms changed the measurement instead of only its sign.
    Taking the maximum over both arms is symmetric in them, which is what keeps a
    forward and a reversed run comparable.
    """
    counts = []
    for arm in arms:
        count = 1
        while arm.batch(count) < target_nanoseconds:
            count *= 2
        counts.append(count)
    return max(counts)


def warm_up(arms, batch_count):
    """Run one discarded batch on every arm so none enters measurement cold.

    Calibration used to leave only the baseline arm warm, biasing the paired
    difference against whichever arm sat in the candidate slot. An A/A control
    cannot reveal that, because there both arms hold identical code.
    """
    for arm in arms:
        arm.batch(batch_count)


def run_rounds(baseline, candidate, batch_count, rounds):
    """Alternate the arms ABBA, which is the production schedule shape."""
    results = []
    for _ in range(rounds):
        first_a = baseline.batch(batch_count)
        first_b = candidate.batch(batch_count)
        second_b = candidate.batch(batch_count)
        second_a = baseline.batch(batch_count)
        results.append({"a": [first_a, second_a], "b": [first_b, second_b]})
    return results


def direction_schedule():
    """Order the direction runs ABBA so neither is systematically measured first.

    Running forward then reverse put forward immediately after the rebuild every time,
    which is its own asymmetry: it reintroduced a +0.511% order bias after the warm-up
    fix had removed a comparable one. This is the same counterbalancing the batch schedule
    already applies within a round, lifted to the direction level.
    """
    return ["forward", "reverse", "reverse", "forward"]


def run_both_directions(arguments):
    """Measure both directions on an ABBA schedule, then report the antisymmetric estimate."""
    pairs = {
        "forward": (arguments.baseline_core, arguments.candidate_core),
        "reverse": (arguments.candidate_core, arguments.baseline_core),
    }
    collected = {"forward": [], "reverse": []}
    runs = []
    for name in direction_schedule():
        baseline, candidate = pairs[name]
        completed = subprocess.run(
            [
                sys.executable, str(pathlib.Path(__file__).resolve()),
                "--baseline-core", str(baseline),
                "--candidate-core", str(candidate),
                "--columns", str(arguments.columns),
                "--rows", str(arguments.rows),
                "--clip-rows", str(arguments.clip_rows),
                "--workload", arguments.workload,
                "--rounds", str(arguments.rounds),
            ],
            check=True, capture_output=True, text=True,
        )
        report = json.loads(completed.stdout)
        collected[name].extend(report["summary"]["pairedValuesPercent"])
        runs.append({"direction": name, "report": report})
    estimate = antisymmetric_estimate(collected["forward"], collected["reverse"])
    return {
        "schemaVersion": 1,
        "mode": "both-directions",
        "directionSchedule": direction_schedule(),
        "estimate": estimate,
        "runs": runs,
        "note": (
            "realEffectPercent is the claimable number: negative means the candidate "
            "revision is faster. orderBiasPercent should sit near zero; a large value "
            "means the measurement is asymmetric and neither direction can be trusted "
            "on its own."
        ),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--baseline-core", type=pathlib.Path, default=DEFAULT_CORE,
        help="TerminalCore checkout for the baseline arm (default: this tree)")
    parser.add_argument(
        "--candidate-core", type=pathlib.Path, default=DEFAULT_CORE,
        help="TerminalCore checkout for the candidate arm; defaults to the baseline "
             "checkout, which makes the run an A/A control")
    parser.add_argument("--columns", type=int, default=160)
    parser.add_argument("--rows", type=int, default=50)
    parser.add_argument(
        "--clip-rows", type=int, default=4,
        help="rows of damage to clip to; 0 measures the full frame")
    parser.add_argument(
        "--workload", choices=WORKLOADS, default="btop-shaped",
        help="content the grid is filled with. 'btop-shaped' is dense sprite art, which "
             "the executor draws as rects and which reaches CoreText's glyph calls zero "
             "times; 'text-shaped' is printable ASCII, the only one of the two that "
             "measures the glyph path at all")
    parser.add_argument("--rounds", type=int, default=8)
    parser.add_argument(
        "--both-directions", action="store_true",
        help="measure forward and reversed, then report the antisymmetric estimate. "
             "Required for any claim about two revisions: a single direction carries an "
             "order bias that does not reverse with the arms. Runs as two processes "
             "because dlopen caches within one, so load order cannot otherwise differ")
    parser.add_argument(
        "--threshold", type=float, default=None,
        help="optional caller-supplied directional threshold in percent. No decision rule "
             "is frozen for this instrument, so omitting this reports statistics only")
    parser.add_argument("--equivalence-band", type=float, default=0.0)
    arguments = parser.parse_args()

    validate_module_names(BASELINE_MODULE, CANDIDATE_MODULE)
    ARTIFACTS.mkdir(parents=True, exist_ok=True)

    if arguments.both_directions:
        json.dump(
            run_both_directions(arguments), sys.stdout, indent=2, sort_keys=True
        )
        sys.stdout.write("\n")
        return

    baseline_library = build_arm(BASELINE_MODULE, arguments.baseline_core, ARTIFACTS)
    candidate_library = build_arm(CANDIDATE_MODULE, arguments.candidate_core, ARTIFACTS)

    baseline = Arm(baseline_library)
    candidate = Arm(candidate_library)
    for arm in (baseline, candidate):
        arm.prepare(
            arguments.columns, arguments.rows, arguments.clip_rows, arguments.workload
        )

    batch_count = calibrate_batch_count([baseline, candidate])
    warm_up([baseline, candidate], batch_count)
    rounds = run_rounds(baseline, candidate, batch_count, arguments.rounds)
    quartets = paired_quartets(rounds)

    is_control = (
        pathlib.Path(arguments.baseline_core).resolve()
        == pathlib.Path(arguments.candidate_core).resolve()
    )
    report = {
        "schemaVersion": 1,
        "geometry": {
            "columns": arguments.columns,
            "rows": arguments.rows,
            "clipRows": arguments.clip_rows,
        },
        "workload": arguments.workload,
        "batchCount": batch_count,
        "isSelfControl": is_control,
        "baselineCore": str(pathlib.Path(arguments.baseline_core).resolve()),
        "candidateCore": str(pathlib.Path(arguments.candidate_core).resolve()),
        "summary": summarize(quartets),
    }
    if arguments.threshold is not None:
        report["decision"] = CAL.decide(
            [value for quartet in quartets for value in quartet],
            directional_threshold=arguments.threshold,
            equivalence_band=arguments.equivalence_band,
            estimator="median",
        )
        report["decision"]["thresholdSource"] = "caller-supplied; not a frozen rule"
    json.dump(report, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
